apiVersion: v1
kind: Secret 
metadata:
  name: name: {{ .Release.Name }}-{{ .Chart.Name }}-secret 
type: Opaque
data:
  consumer_key: {{ .Value.secret.consumer_key }}
  consumer_secret: {{ .Value.secret.consumer_secret }}
  access_token: {{ .Value.secret.access_token }}
  access_token_sec: {{ .Value.secret.access_token_sec }}
