apiVersion: v1
kind: Secret 
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret 
type: Opaque
data:
  consumer_key: {{ .Values.secret.consumer_key }}
  consumer_secret: {{ .Values.secret.consumer_secret }}
  access_token: {{ .Values.secret.access_token }}
  access_token_sec: {{ .Values.secret.access_token_sec }}
